language: cpp

compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install debhelper qt5-qmake qt5-default qtbase5-dev qtdeclarative5-dev libqt5opengl5-dev libqt5webkit5-dev libxslt1-dev libxml2-dev libgstreamer0.10-dev libglib2.0-dev libsqlite3-dev libgstreamer-plugins-base0.10-dev

script:
  - qmake -project
  - qmake hello.pro
  - make

branches:
  only:
    - master

notifications:
  email:
    - anak10thn@gmail.com
