language: cpp

compiler: gcc

script: pdebuild --use-pdebuild-internal --architecture $PKGARCH

install: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pbuilder devscripts eatmydata
  - wget http://ftp.kr.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.48+deb7u1_all.deb -O /home/travis/debootstrap.deb
  - wget http://ftp.kr.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2014.1~deb7u1_all.deb -O /home/travis/debian-archive-keyring.deb
  - sudo dpkg -i /home/travis/*.deb
  - mkdir -p /home/travis/builder/result/$PKGARCH
  - echo "BUILDRESULT=/home/travis/builder/result/$PKGARCH" > /home/travis/.pbuilderrc
  - sudo pbuilder create --distribution testing --architecture $PKGARCH --mirror http://ftp.us.debian.org/debian/ --allow-untrusted --debootstrapopts --no-check-gpg --debootstrapopts --variant=buildd

branches:
  only:
    - master

notifications:
  email:
    - anak10thn@gmail.com

env:
  matrix:
    - PKGARCH=i386
    - PKGARCH=amd64
