language: cpp

compiler: gcc

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt531
  - sudo apt-get update -qq
  - sudo apt-get install -qq debhelper qt5-qmake qt5-default qtbase5-dev qtdeclarative5-dev libqt5opengl5-dev libqt5webkit5-dev libxslt1-dev libxml2-dev libgstreamer0.10-dev libglib2.0-dev libsqlite3-dev libgstreamer-plugins-base0.10-dev

script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make

branches:
  only:
    - master

notifications:
  email:
    - anak10thn@gmail.com
