language: cpp

compiler: gcc

install:
  - brew install qt5

script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make

branches:
  only:
    - master

notifications:
  email:
    - anak10thn@gmail.com
