.TH IGNSDK 1 "February 21, 2015" "Version 1.1.6" "IGNSDK - General Commands Manual"
.SH NAME
IGNSDK \- IGOS Nusantara Software Development Kit
.SH SYNOPSIS
ignsdk [-p|--project \fBproject_dir\fR] [-f|--file \fBfile\fR] [-d|--development] [-r|--remote \fBport\fR] [-v|--version] [-h|--help]
.SH DESCRIPTION
.PP
IGNSDK is a Software Development Kit (SDK) designed specifically for developing hybrid applications in IGOS Nusantara. But, now also available for other Linux distributions, 
such as Archlinux, Slackware, Ubuntu, and Debian. You can write desktop applications in HTML and Javascript language with IGNSDK.
.PP
\fBHomepage:\fR http://ignsdk.web.id
.br
\fBFull documentation:\fR https://github.com/anak10thn/ignsdk-qt/wiki
.SH OPTIONS
.IP "-p, --project \fBproject_dir\fR" 30
Run application. \fBproject_dir\fR must contain both index.html and ignsdk.json.
.IP "-f, --file" 30
Load specific HTML file instead of index.html
.IP "-d, --development" 30
Activate development mode (Web Inspector).
.IP "-r, --remote \fBport\fR" 30
Set port number for remote debugging.
.IP "-v, --version" 30
Show IGNSDK version.
.IP "-h, --help" 30
Show help.
.SH BUGS
.PP
See https://github.com/anak10thn/ignsdk-qt/issues/
.SH "SEE ALSO"
.PP
\fBignsdk-app-creator\fR(1), \fBignsdk-app-builder\fR(1)
.SH AUTHOR
This manual page was written by Surya Handika Putratama <ubunteroz@gmail.com>.
