.TH IGNSDK 1 "December 3, 2013" "Version 1.1.3" "IGNSDK - General Commands Manual"
.SH NAME
IGNSDK \- IGOS Nusantara Software Development Kit
.SH SYNOPSIS
ignsdk [-d] [-v] [-r \fBport\fR] [-p \fBproject_dir\fR]
.SH DESCRIPTION
.PP
IGNSDK is a Software Development Kit (SDK) designed specifically for developing hybrid applications in IGOS Nusantara. But, now also available for other Linux distributions, 
such as Archlinux, Slackware, Ubuntu, and Debian. You can write desktop applications in HTML and Javascript language with IGNSDK.
.PP
Homepage: http://ignsdk.web.id
.br
Full documentation: https://github.com/anak10thn/ignsdk-qt/wiki
.SH OPTIONS
.IP "\-d, \-\-dev" 30
Activate debug mode (Web Inspector).
.IP "\-p \fBproject_dir\fR" 30
Run application. \fBproject_dir\fR must contain both index.html and ignsdk.json.
.IP "\-r, \-\-dev-remote \fBport\fR" 30
Set port number for remote debugging.
.IP "\-v, --version" 30
Show IGNSDK version.
.SH BUGS
.PP
See https://github.com/anak10thn/ignsdk-qt/issues/
.SH "SEE ALSO"
.PP
\fBignsdk-app-creator\fR(1), \fBignsdk-app-builder\fR(1)
.SH AUTHOR
This manual page was written by IGNSDK Developers.
